# -*- coding: utf-8 -*-
"""day29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gI3QqMi4Q_NZ40ZFWou6OK_nlcj6b8tK
"""

#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/Wholesale customers data.csv")

df.head()

df.info()

df.drop(['Channel','Region'],axis=1,inplace=True)

df

array=df.values

array

stscaler = StandardScaler().fit(array)
X = stscaler.transform(array)

X

from sklearn.cluster import AgglomerativeClustering

group=AgglomerativeClustering(n_clusters=3)
group.fit_predict(X)

cluster=group.fit_predict(X)

cluster

from sklearn.metrics import silhouette_score
silhouette_score(X,cluster)

from sklearn.cluster import KMeans

wcss=[]
for i in range(1,11):
    kmeans=KMeans(n_clusters=i,random_state=0)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

wcss

plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

group_num=pd.DataFrame(cluster,columns=['Group'])
group_num

model=KMeans(n_clusters=4,random_state=309)
groups=model.fit_predict(X)

groups

groups.shape

df.head()

cust_KMeans_data=pd.concat([df,pd.DataFrame(groups,columns=['Group'])],axis=1)
cust_KMeans_data

silhouette_score(X,groups)

