# -*- coding: utf-8 -*-
"""day27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gI3QqMi4Q_NZ40ZFWou6OK_nlcj6b8tK
"""

#import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv(r"/content/Wholesale customers data.csv")
df.head()

df.drop(['Channel','Region'],axis=1,inplace=True)
df.head()

array=df.values

array

stscaler =  StandardScaler()
X = stscaler.fit_transform(array)

X

dbscan = DBSCAN(eps=0.8, min_samples=6)
dbscan.fit(X)

